---
- name: Instalando pacotes essenciais APT
  apt:
   name: "{{pacotes}}"
   state: present
  when: ansible_pkg_mgr == "apt"

- name: Instalando pacotes essenciais YUM
  yum:
   name: "{{pacotes}}"
   state: present
  when: ansible_pkg_mgr == "yum"
...